<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220002209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE market_collection_logs ADD collected_date DATE NOT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ADD total_units_scraped INT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ADD total_snapshots_saved INT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ADD error_message TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ADD duration_seconds DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE market_collection_logs DROP procedure_tuss');
        $this->addSql('ALTER TABLE market_collection_logs DROP total_units');
        $this->addSql('ALTER TABLE market_collection_logs DROP total_snapshots');
        $this->addSql('ALTER TABLE market_collection_logs DROP execution_time_ms');
        $this->addSql('ALTER TABLE market_collection_logs ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE market_collection_logs ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE market_collection_logs ALTER status TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE market_collection_logs ALTER status SET NOT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE market_collection_logs ALTER created_at SET NOT NULL');
        $this->addSql('DROP INDEX uniq_daily_snapshot');
        $this->addSql('ALTER TABLE market_price_snapshots ADD collected_date DATE NOT NULL');
        $this->addSql('ALTER TABLE market_price_snapshots ADD raw_price_text VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_price_snapshots ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE market_price_snapshots DROP distance');
        $this->addSql('ALTER TABLE market_price_snapshots DROP collected_at');
        $this->addSql('ALTER TABLE market_price_snapshots DROP source');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER unit_id SET NOT NULL');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER procedure_id SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_daily_snapshot ON market_price_snapshots (procedure_id, unit_id, collected_date)');
        $this->addSql('ALTER TABLE market_procedures ADD code VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_procedures ADD category VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_procedures DROP tuss_code');
        $this->addSql('ALTER TABLE market_procedures ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE market_procedures ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE market_procedures ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE market_procedures RENAME COLUMN type TO rating');
        $this->addSql('ALTER TABLE market_units ADD name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE market_units ADD company_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units ADD rating NUMERIC(3, 1) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units DROP partner_id');
        $this->addSql('ALTER TABLE market_units DROP social_name');
        $this->addSql('ALTER TABLE market_units DROP facility_name');
        $this->addSql('ALTER TABLE market_units DROP neighborhood');
        $this->addSql('ALTER TABLE market_units DROP zipcode');
        $this->addSql('ALTER TABLE market_units DROP address_line');
        $this->addSql('ALTER TABLE market_units DROP number');
        $this->addSql('ALTER TABLE market_units DROP rating_avg');
        $this->addSql('ALTER TABLE market_units DROP rating_count');
        $this->addSql('ALTER TABLE market_units ALTER state TYPE VARCHAR(2)');
        $this->addSql('ALTER TABLE market_units ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE market_units ALTER created_at SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE market_collection_logs ADD procedure_tuss VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ADD total_units INT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ADD total_snapshots INT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ADD execution_time_ms INT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_collection_logs DROP collected_date');
        $this->addSql('ALTER TABLE market_collection_logs DROP total_units_scraped');
        $this->addSql('ALTER TABLE market_collection_logs DROP total_snapshots_saved');
        $this->addSql('ALTER TABLE market_collection_logs DROP error_message');
        $this->addSql('ALTER TABLE market_collection_logs DROP duration_seconds');
        $this->addSql('ALTER TABLE market_collection_logs ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE market_collection_logs ALTER id SET DEFAULT nextval(\'market_collection_logs_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE market_collection_logs ALTER status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE market_collection_logs ALTER status DROP NOT NULL');
        $this->addSql('ALTER TABLE market_collection_logs ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE market_collection_logs ALTER created_at DROP NOT NULL');
        $this->addSql('DROP INDEX uniq_daily_snapshot');
        $this->addSql('ALTER TABLE market_price_snapshots ADD distance NUMERIC(10, 3) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_price_snapshots ADD collected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE market_price_snapshots ADD source VARCHAR(50) DEFAULT \'medprev\'');
        $this->addSql('ALTER TABLE market_price_snapshots DROP collected_date');
        $this->addSql('ALTER TABLE market_price_snapshots DROP raw_price_text');
        $this->addSql('ALTER TABLE market_price_snapshots DROP created_at');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER id SET DEFAULT nextval(\'market_price_snapshots_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER procedure_id DROP NOT NULL');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER unit_id DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_daily_snapshot ON market_price_snapshots (unit_id, procedure_id)');
        $this->addSql('ALTER TABLE market_procedures ADD tuss_code VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE market_procedures DROP code');
        $this->addSql('ALTER TABLE market_procedures DROP category');
        $this->addSql('ALTER TABLE market_procedures ALTER name TYPE TEXT');
        $this->addSql('ALTER TABLE market_procedures ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE market_procedures ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE market_procedures RENAME COLUMN rating TO type');
        $this->addSql('ALTER TABLE market_units ADD partner_id UUID NOT NULL');
        $this->addSql('ALTER TABLE market_units ADD facility_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units ADD neighborhood VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units ADD zipcode VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units ADD address_line VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units ADD number VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units ADD rating_avg NUMERIC(4, 3) DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units ADD rating_count INT DEFAULT NULL');
        $this->addSql('ALTER TABLE market_units DROP name');
        $this->addSql('ALTER TABLE market_units DROP rating');
        $this->addSql('ALTER TABLE market_units ALTER state TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE market_units ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE market_units ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE market_units RENAME COLUMN company_name TO social_name');
    }
}
