<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260226160313 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE market_collection_logs ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE market_collection_logs ALTER created_at SET NOT NULL');
        $this->addSql('DROP INDEX uniq_daily_snapshot');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER collected_at SET NOT NULL');
        $this->addSql('ALTER TABLE market_procedures ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE market_units ALTER created_at SET NOT NULL');
        $this->addSql('DROP INDEX idx_radar_sessions_updated');
        $this->addSql('ALTER TABLE radar_sessions ALTER title DROP DEFAULT');
        $this->addSql('ALTER TABLE radar_sessions ALTER history TYPE JSON');
        $this->addSql('ALTER TABLE radar_sessions ALTER history DROP DEFAULT');
        $this->addSql('ALTER TABLE radar_sessions ALTER responses TYPE JSON');
        $this->addSql('ALTER TABLE radar_sessions ALTER responses DROP DEFAULT');
        $this->addSql('ALTER TABLE radar_sessions ALTER msgs TYPE JSON');
        $this->addSql('ALTER TABLE radar_sessions ALTER msgs DROP DEFAULT');
        $this->addSql('ALTER TABLE radar_sessions ALTER msg_count DROP DEFAULT');
        $this->addSql('ALTER TABLE radar_sessions ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE radar_sessions ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE radar_sessions ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE radar_sessions ALTER updated_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE market_collection_logs ALTER id SET DEFAULT nextval(\'market_collection_logs_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE market_collection_logs ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER id SET DEFAULT nextval(\'market_price_snapshots_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE market_price_snapshots ALTER collected_at DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_daily_snapshot ON market_price_snapshots (unit_id, procedure_id)');
        $this->addSql('ALTER TABLE market_procedures ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE market_units ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE radar_sessions ALTER title SET DEFAULT \'Sessão sem título\'');
        $this->addSql('ALTER TABLE radar_sessions ALTER history TYPE JSONB');
        $this->addSql('ALTER TABLE radar_sessions ALTER history SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE radar_sessions ALTER responses TYPE JSONB');
        $this->addSql('ALTER TABLE radar_sessions ALTER responses SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE radar_sessions ALTER msgs TYPE JSONB');
        $this->addSql('ALTER TABLE radar_sessions ALTER msgs SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE radar_sessions ALTER msg_count SET DEFAULT 0');
        $this->addSql('ALTER TABLE radar_sessions ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE radar_sessions ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE radar_sessions ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE radar_sessions ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('CREATE INDEX idx_radar_sessions_updated ON radar_sessions (updated_at)');
    }
}
